# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-07 16:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='ftp_username',
            field=models.CharField(default=django.utils.timezone.now, max_length=32, verbose_name='FTP Username'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='company',
            name='company_type',
            field=models.CharField(choices=[('SO', 'Software developer'), ('MA', 'Manufacturer'), ('RE', 'Reseller'), ('MI', 'Miner'), ('HO', 'Hosting')], max_length=2, verbose_name='Type'),
        ),
    ]
