# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-07 16:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_auto_20170507_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='ftp_password',
            field=models.CharField(default=django.utils.timezone.now, max_length=32, verbose_name='FTP Password'),
            preserve_default=False,
        ),
    ]
