# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-12 09:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_auto_20170510_1243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='ftp_login',
        ),
        migrations.RemoveField(
            model_name='company',
            name='ftp_password',
        ),
    ]
