# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-05 11:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_auto_20170512_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_type',
            field=models.CharField(choices=[('SO', 'Software developer'), ('MA', 'Manufacturer'), ('RE', 'Reseller'), ('MI', 'Miner'), ('HO', 'Hosting'), ('IN', 'Integrator')], max_length=2, verbose_name='Type'),
        ),
    ]
