# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-17 21:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backupfirewall',
            name='site_name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='backuprouter',
            name='site_name',
            field=models.CharField(max_length=64),
        ),
    ]
