# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backups', '0002_auto_20170424_0117'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoreBackup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('time_interval', models.IntegerField(default=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='backupfirewall',
            name='object_backup',
        ),
        migrations.RemoveField(
            model_name='backuprouter',
            name='object_backup',
        ),
        migrations.DeleteModel(
            name='BackupFirewall',
        ),
        migrations.DeleteModel(
            name='BackupRouter',
        ),
    ]
