# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 13:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('netobjects', '0006_auto_20170426_1639'),
        ('backups', '0003_auto_20170426_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='corebackup',
            name='object_backup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='netobjects.CoreNetworkObject'),
        ),
    ]
