# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 10:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backups', '0004_corebackup_object_backup'),
    ]

    operations = [
        migrations.AddField(
            model_name='corebackup',
            name='ftp_user_login',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='corebackup',
            name='ftp_user_password',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='corebackup',
            name='last_backup_status',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
