# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 10:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backups', '0005_auto_20170503_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='corebackup',
            name='ftp_server_address',
            field=models.CharField(default='', max_length=20),
        ),
    ]
