# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 11:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backups', '0006_corebackup_ftp_server_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corebackup',
            name='last_backup_status',
            field=models.TextField(blank=True),
        ),
    ]
