# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-07 15:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backups', '0008_auto_20170507_1821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='corebackup',
            name='ftp_server_address',
        ),
    ]
