# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-16 20:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Firewall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('web_address', models.CharField(default='https://', max_length=29)),
                ('cli_access_port', models.IntegerField(default=22)),
                ('login', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('manufacturer', models.CharField(default='', max_length=20)),
                ('model_version', models.CharField(default='', max_length=20, verbose_name='Model')),
                ('cli_address', models.CharField(blank=True, max_length=255, null=True)),
                ('ipv4_external_address', models.CharField(blank=True, max_length=255, null=True)),
                ('dns_address', models.CharField(blank=True, max_length=255, null=True)),
                ('object_type', models.CharField(default='firewall', max_length=32)),
                ('site_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.Site')),
            ],
            options={
                'abstract': False,
                'ordering': ('site_name',),
            },
        ),
        migrations.CreateModel(
            name='Router',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('web_address', models.CharField(default='https://', max_length=29)),
                ('cli_access_port', models.IntegerField(default=22)),
                ('login', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('manufacturer', models.CharField(default='', max_length=20)),
                ('model_version', models.CharField(default='', max_length=20, verbose_name='Model')),
                ('cli_address', models.CharField(blank=True, max_length=255, null=True)),
                ('ipv4_external_address', models.CharField(blank=True, max_length=255, null=True)),
                ('dns_address', models.CharField(blank=True, max_length=255, null=True)),
                ('object_type', models.CharField(default='router', max_length=32)),
                ('site_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.Site')),
            ],
            options={
                'abstract': False,
                'ordering': ('site_name',),
            },
        ),
    ]
