# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 19:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netobjects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='firewall',
            options={},
        ),
        migrations.AlterModelOptions(
            name='router',
            options={},
        ),
        migrations.AlterField(
            model_name='firewall',
            name='dns_address',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='firewall',
            name='ipv4_external_address',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='firewall',
            name='object_type',
            field=models.CharField(default='firewall', editable=False, max_length=32),
        ),
        migrations.AlterField(
            model_name='router',
            name='dns_address',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='router',
            name='ipv4_external_address',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='router',
            name='object_type',
            field=models.CharField(default='router', editable=False, max_length=32),
        ),
    ]
