# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-15 23:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netobjects', '0002_auto_20170416_0138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firewall',
            name='ipv4_address',
            field=models.GenericIPAddressField(),
        ),
    ]
