# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-15 23:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netobjects', '0003_auto_20170416_0219'),
    ]

    operations = [
        migrations.AddField(
            model_name='firewall',
            name='port',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
