# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-16 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netobjects', '0004_firewall_port'),
    ]

    operations = [
        migrations.RenameField(
            model_name='firewall',
            old_name='ipv4_address',
            new_name='ipv4_external_address',
        ),
        migrations.RenameField(
            model_name='firewall',
            old_name='port',
            new_name='web_access_port',
        ),
        migrations.AddField(
            model_name='firewall',
            name='cli_access_port',
            field=models.IntegerField(default=22, null=True),
        ),
        migrations.AddField(
            model_name='firewall',
            name='cli_address',
            field=models.CharField(default='', max_length=21),
        ),
        migrations.AddField(
            model_name='firewall',
            name='web_address',
            field=models.CharField(max_length=29, null=True),
        ),
    ]
