# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-16 12:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netobjects', '0005_auto_20170416_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firewall',
            name='cli_address',
            field=models.CharField(blank=True, max_length=21),
        ),
        migrations.AlterField(
            model_name='firewall',
            name='ipv4_external_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='firewall',
            name='web_access_port',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
