# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 13:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('backups', '0003_auto_20170426_1639'),
        ('netobjects', '0005_auto_20170421_1645'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoreNetworkObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('web_address', models.CharField(default='https://', max_length=100)),
                ('cli_access_port', models.IntegerField(default=22)),
                ('login', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('cli_address', models.CharField(blank=True, editable=False, max_length=255)),
                ('ipv4_external_address', models.CharField(blank=True, editable=False, max_length=255)),
                ('dns_address', models.CharField(blank=True, editable=False, max_length=255)),
                ('site_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.Site')),
                ('spec_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='netobjects.BluePrintNetworkObject')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='firewall',
            name='site_name',
        ),
        migrations.RemoveField(
            model_name='firewall',
            name='spec_model',
        ),
        migrations.RemoveField(
            model_name='router',
            name='site_name',
        ),
        migrations.RemoveField(
            model_name='router',
            name='spec_model',
        ),
        migrations.DeleteModel(
            name='Firewall',
        ),
        migrations.DeleteModel(
            name='Router',
        ),
    ]
