# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netobjects', '0006_auto_20170426_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corenetworkobject',
            name='cli_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='corenetworkobject',
            name='dns_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='corenetworkobject',
            name='ipv4_external_address',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
