# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-07 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netobjects', '0007_auto_20170426_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blueprintnetworkobject',
            name='object_type',
            field=models.CharField(choices=[('FI', 'Firewall'), ('RO', 'Router'), ('SW', 'Switch'), ('AC', 'Access Point'), ('IP', 'IPPBX'), ('HA', 'Hardware Server')], max_length=2),
        ),
    ]
